apiVersion: v1
kind: ServiceAccount
metadata:
  name: observer
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: observer
rules:
  - apiGroups:
      - ""
    resources:
      - "namespaces"
      - "events"
    verbs:
      - "get"
      - "list"
      - "create"
      - "update"
      - "delete"
      - "patch"
      - "watch"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: observer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: observer
subjects:
  - kind: ServiceAccount
    name: observer
    namespace: default
